import os
import json
from typing import Dict, Any
from pydantic import BaseModel, Field
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

class RoomCounts(BaseModel):
    bedrooms: int = Field(default=0)
    bathrooms: int = Field(default=0)
    kitchens: int = Field(default=0)
    living_rooms: int = Field(default=0)
    offices: int = Field(default=0)
    outside_kitchens: int = Field(default=0, description="Outdoor or annex kitchens")
    outside_bathrooms: int = Field(default=0, description="Outdoor or annex bathrooms")
    maid_rooms: int = Field(default=0, description="Maid or staff rooms in the annex")
    corridors: int = Field(default=0, description="Connecting hallways")

class ExtractorSchema(BaseModel):
    plot_size: float | None = Field(default=600.0, description="Plot size in sqm. Default to 600 if not specified.")
    floors: int | None = Field(default=1, description="Number of floors. Default to 1.")
    usage: str | None = Field(default="residential", description="Usage type: residential, commercial, industrial, or mixed-use.")
    parking_spaces: int | None = Field(default=0, description="Number of parking spaces.")
    rooms: RoomCounts
    archetype: str | None = Field(default="auto", description="Preferred layout archetype: 'auto', 'central_corridor', 'single_loaded', 'courtyard', or 'l_shape'. Defaults to auto.")

def extract_parameters_from_history(messages: list[dict]) -> Dict[str, Any]:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY environment variable is missing. Please create a .env file and add your key.")
        
    from google import genai
    from google.genai import types
    
    client = genai.Client()
    
    # Format the conversation history into a single string for context
    history_text = ""
    for msg in messages:
        role = "User" if msg["role"] == "user" else "Assistant"
        history_text += f"{role}: {msg['content']}\n\n"
        
    prompt = f"""
    You are an expert architectural assistant. You are participating in a conversation with a user about a building design.
    Based on the ENTIRE conversation history below, extract the CURRENT, FINAL building parameters, room counts, and preferred layout style.
    
    Rules for Extraction:
    1. Count the number of each type of room requested by the user.
    2. If the user mentions a layout style like 'U-shaped' (courtyard), 'L-shaped' (l_shape), 'narrow' (single_loaded), or 'standard' (central_corridor), set the archetype appropriately. Otherwise, leave it as 'auto'.
    3. Always ensure standard rooms exist even if the user only specifies a subset (e.g., if they say "2-bedroom home", infer there must be a living room and a kitchen).
    4. If the user asks for bedrooms or living spaces in a separate annex, guest house, or outdoor area, classify those specific rooms as "maid_rooms", "outside_kitchens", or "outside_bathrooms".
    
    CONVERSATION HISTORY:
    {history_text}
    """
    
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=ExtractorSchema,
            temperature=0.1,
        ),
    )
    
    try:
        data = json.loads(response.text)
        return data
    except Exception as e:
        raise ValueError(f"Failed to parse AI output: {e}")

def extract_parameters(description: str) -> Dict[str, Any]:
    # Backward compatibility for the /analyze endpoint
    return extract_parameters_from_history([{"role": "user", "content": description}])

def generate_summary(messages: list[dict], params: dict, compliance: dict) -> str:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return "I've updated the layout based on your request."
        
    from google import genai
    from google.genai import types
    
    client = genai.Client()
    
    history_text = ""
    for msg in messages:
        role = "User" if msg["role"] == "user" else "Assistant"
        history_text += f"{role}: {msg['content']}\n\n"
        
    prompt = f"""
    You are an expert architectural assistant. You just generated a new procedural floor plan based on the user's latest request.
    
    Here is the conversation history so far:
    {history_text}
    
    Here is the final layout specification that was just generated by the architectural engine:
    {json.dumps(params, indent=2)}
    
    Write a short, friendly, conversational response (1-3 sentences) to the user summarizing what you just built for them.
    Highlight any specific architectural style or archetype (e.g., L-shaped, central corridor) if one was chosen, and confirm the room counts. 
    Make it read naturally, as if you are presenting the updated design.
    """
    
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.4,
        ),
    )
    
    return response.text.strip()

