import React from 'react';

export default function Terms({ onBack }) {
  return (
    <div className="auth-layout" style={{ alignItems: 'flex-start', padding: '40px 20px', overflowY: 'auto' }}>
      <div className="card" style={{ maxWidth: '800px', width: '100%', margin: '0 auto', textAlign: 'left' }}>
        <div className="corner-bl"></div><div className="corner-br"></div>
        <button className="btn-secondary" onClick={onBack} style={{ marginBottom: '20px' }}>
          ← Back
        </button>
        <h1 style={{ marginTop: 0, color: 'var(--text-hi)' }}>Terms of Service</h1>
        <p className="subhead">Last updated: June 2026</p>
        
        <div style={{ color: 'var(--text-lo)', lineHeight: 1.6, display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <p>Welcome to AI Architect! By accessing or using our platform, you agree to be bound by these Terms of Service.</p>
          
          <h3 style={{ color: 'var(--text-hi)', marginTop: '10px' }}>1. Use of Service</h3>
          <p>AI Architect provides an AI-powered design and floor plan generation tool. You agree to use this service only for lawful purposes and in accordance with these Terms.</p>
          
          <h3 style={{ color: 'var(--text-hi)', marginTop: '10px' }}>2. User Accounts</h3>
          <p>To use our platform, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>
          
          <h3 style={{ color: 'var(--text-hi)', marginTop: '10px' }}>3. Intellectual Property</h3>
          <p>The designs, floor plans, and architectures generated by AI Architect based on your prompts are granted to you for your use. However, AI Architect retains the rights to the underlying models, software, and interface design.</p>
          
          <h3 style={{ color: 'var(--text-hi)', marginTop: '10px' }}>4. Limitation of Liability</h3>
          <p>The floor plans generated by AI Architect are conceptual and informational. They do not constitute official engineering or architectural blueprints. You must consult licensed professionals before beginning any construction based on our outputs.</p>
          
          <h3 style={{ color: 'var(--text-hi)', marginTop: '10px' }}>5. Termination</h3>
          <p>We reserve the right to suspend or terminate your access to the service at any time for violations of these Terms.</p>
        </div>
      </div>
    </div>
  );
}
